--FIND total customers by countries
select
country,
count(customer_key) as total_customers
from gold.dim_customers
group by country
Order by total_customers DESC
--Find total customers by gender
select
gender,
count(customer_key) as total_customers
from gold.dim_customers
group by gender
Order by total_customers DESC
--Find total products by category
select
category,
count(product_key) as total_product
from gold.dim_products
group by category
Order by total_product DESC
--What is the average cost in each category?
select
category,
AVG(cost) average_cost
from gold.dim_products
group by category 
Order by average_cost desc

--What is the total revenue generated for each category?
select 
dp.category,
sum(fs.sales_amount) as total_revenue
from gold.fact_sales fs
LEFT JOIN gold.dim_products dp
ON dp.product_key = fs.product_key
group by dp.category

--Find total revenue generated by each customer
select 
dc.customer_key,
dc.first_name,
dc.last_name,
SUM(fs.sales_amount) as total_revenue
from gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
ON fs.customer_key = dc.customer_key
group by dc.customer_key,
dc.first_name,
dc.last_name
Order by total_revenue;
--What is the distribution of sold items across countries?
select
dc.country,
sum(fs.quantity) total_sold_quantity
from gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
ON fs.customer_key = dc.customer_key 
group by dc.country
